name: esmfold
channels:
  - pytorch
  - conda-forge
  - defaults
  - apple
dependencies:
  - python=3.8
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - openpyxl
  - conda-forge::pdbfixer
  - einops=0.6.1
  - pyyaml=5.4.1
  - pip
  - pandas
  - biopython
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - ipykernel
  - pip:
    - omegaconf
    - fair-esm
    - fairscale
    - "fair-esm[esmfold]" 